- hosts: localhost
  tasks:
    - name: Create ALB Target Group
      elb_target_group:
        state: present
        name: "{{ target_group_name }}"
        protocol: http
        port: 80
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"

    - name: Add HTTP listener rules
      elb_application_lb:
        state: present
        name: "{{ alb_name }}"
        subnets:
          - "{{ subnet_id_1 }}"
          - "{{ subnet_id_2 }}"
        security_groups:
          - "{{ security_group }}"
        region: "{{ region }}"
        listeners:
          - Protocol: HTTP
            Port: 80
            DefaultActions:
              - Type: forward
                TargetGroupName: "{{ target_group_name }}"
    
    - name: Add EC2 instance
      ec2:
        region: "{{ region }}"
        state: present
        key_name: "{{ keyname }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ami_id }}"
        wait: yes
        wait_timeout: 500
        count: "{{ ec2_count }}"
        volumes:
        - device_name: /dev/sda1
          volume_size: "{{ volume_size }}"
        monitoring: yes
        vpc_subnet_id: "{{ ec2_subnet_id }}"
      register: ec2
    - debug: var=ec2.instance_ids

    - name: Attach to target group
      elb_target:
        target_group_name: "{{ target_group_name }}"
        target_id: "{{ item }}"
        state: present
        region: "{{ region }}"
      with_items: "{{ ec2.instance_ids  }}"